# Generated by Django 2.2.1 on 2019-05-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
                ('active', models.BooleanField()),
                ('content', models.TextField()),
            ],
        ),
    ]
